const corrections = {
    "accomodate": "accommodate",
    "achieve": "achieve",
    "agressive": "aggressive",
    "alot": "a lot",
    "amoung": "among",
    "anual": "annual",
    "arguement": "argument",
    "assasinate": "assassinate",
    "athlete": "athlete",
    "begining": "beginning",
    "belive": "believe",
    "buisness": "business",
    "calender": "calendar",
    "caterer": "caterer",
    "cemetary": "cemetery",
    "definately": "definitely",
    "dilemma": "dilemma",
    "dissapear": "disappear",
    "dissapointment": "disappointment",
    "embarras": "embarrass",
    "enviroment": "environment",
    "existance": "existence",
    "fascinate": "fascinate",
    "foriegn": "foreign",
    "freind": "friend",
    "goverment": "government",
    "grateful": "grateful",
    "humerous": "humorous",
    "independant": "independent",
    "intresting": "interesting",
    "judgement": "judgment",
    "liason": "liaison",
    "maintainance": "maintenance",
    "millepede": "millipede",
    "neccessary": "necessary",
    "occured": "occurred",
    "paralel": "parallel",
    "personel": "personal",
    "posession": "possession",
    "privelege": "privilege",
    "recieve": "receive",
    "refered": "referred",
    "relevent": "relevant",
    "seperate": "separate",
    "supercede": "supersede",
    "tommorrow": "tomorrow",
    "untill": "until",
    "wich": "which",
    "writting": "writing",
    "abandon": "abandon",
    "abbreviate": "abbreviate",
    "absent": "absent",
    "abundance": "abundance",
    "acquaintance": "acquaintance",
    "advice": "advice",
    "advisable": "advisable",
    "affect": "affect",
    "agriculture": "agriculture",
    "allegiance": "allegiance",
    "analyze": "analyze",
    "anxiety": "anxiety",
    "apology": "apology",
    "appreciate": "appreciate",
    "argumentative": "argumentative",
    "arrangement": "arrangement",
    "assistance": "assistance",
    "atmosphere": "atmosphere",
    "attitude": "attitude",
    "available": "available",
    "beautiful": "beautiful",
    "beneficial": "beneficial",
    "bizarre": "bizarre",
    "calendar": "calendar",
    "celebrate": "celebrate",
    "challenge": "challenge",
    "characteristic": "characteristic",
    "cliché": "cliché",
    "collaborate": "collaborate",
    "commitment": "commitment",
    "communication": "communication",
    "community": "community",
    "complicated": "complicated",
    "congratulate": "congratulate",
    "conscious": "conscious",
    "convenient": "convenient",
    "courageous": "courageous",
    "creativity": "creativity",
    "definitely": "definitely",
    "delicious": "delicious",
    "demonstrate": "demonstrate",
    "dependable": "dependable",
    "description": "description",
    "determination": "determination",
    "development": "development",
    "disappoint": "disappoint",
    "distraction": "distraction",
    "education": "education",
    "efficient": "efficient",
    "emergency": "emergency",
    "encourage": "encourage",
    "environmental": "environmental",
    "essential": "essential",
    "exaggerate": "exaggerate",
    "experience": "experience",
    "fascinating": "fascinating",
    "favorable": "favorable",
    "familiar": "familiar",
    "fascination": "fascination",
    "flourish": "flourish",
    "forbidden": "forbidden",
    "frequently": "frequently",
    "generous": "generous",
    "genuine": "genuine",
    "gratefulness": "gratefulness",
    "guarantee": "guarantee",
    "happiness": "happiness",
    "immediate": "immediate",
    "impressive": "impressive",
    "incredible": "incredible",
    "independent": "independent",
    "influence": "influence",
    "inspiration": "inspiration",
    "intelligent": "intelligent",
    "interesting": "interesting",
    "introduction": "introduction",
    "invitation": "invitation",
    "knowledgeable": "knowledgeable",
    "laughter": "laughter",
    "legitimate": "legitimate",
    "literature": "literature",
    "maintenance": "maintenance",
    "mysterious": "mysterious",
    "necessary": "necessary",
    "occasion": "occasion",
    "opportunity": "opportunity",
    "organization": "organization",
    "participate": "participate",
    "perseverance": "perseverance",
    "persuade": "persuade",
    "philosophy": "philosophy",
    "possibility": "possibility",
    "preference": "preference",
    "professional": "professional",
    "profound": "profound",
    "psychology": "psychology",
    "questionnaire": "questionnaire",
    "realistic": "realistic",
    "recommend": "recommend",
    "relationship": "relationship",
    "reliable": "reliable",
    "remarkable": "remarkable",
    "responsibility": "responsibility",
    "satisfaction": "satisfaction",
    "significant": "significant",
    "situation": "situation",
    "successful": "successful",
    "surprise": "surprise",
    "suspicious": "suspicious",
    "technology": "technology",
    "tremendous": "tremendous",
    "unbelievable": "unbelievable",
    "unfortunate": "unfortunate",
    "valuable": "valuable",
    "variety": "variety",
    "victorious": "victorious",
    "volunteer": "volunteer",
    "wonderful": "wonderful",
    "yesterday": "yesterday",
    "zealous": "zealous",
    // Add more words as needed
};

document.getElementById('correctButton').addEventListener('click', function() {
    let inputText = document.getElementById('inputText').value;
    let correctedText = inputText.split(/\s+/).map(word => {
        // Remove punctuation from the word for checking
        const cleanWord = word.replace(/[.,!?;:()]/g, '').toLowerCase();
        
        // Check if the cleaned word is in the corrections map
        if (corrections[cleanWord]) {
            // Replace with the correct spelling
            return `<span style="color: green;">${corrections[cleanWord]}</span>`; // Highlight corrected words
        }
        return word; // Return the original word if it's correct
    }).join(' ');

    document.getElementById('outputText').innerHTML = correctedText;
});
